### ISSUE TITLE
D2 doesn't have it's exterior hull mapped out like D3 does

### ISSUE THREAD

**Issue by Bamhalazam** [Bamhalazam/Conquest#3]
@Panicat if you have nothing to do you can map out the hull on D2, have it be laid out like deck 3 1:1 and align the staircases. I think I will be tinkering around from mobile and renaming the deck files. I'm not sure how 3 decks would work honestly. We want to run a private experience tho so the lag can't be THAT bad.

**Comment by Panicat** [comment]
Might do that sometime. but no promises ;)

**Comment by Bamhalazam** [comment]
Done, merged alt-hull branch into main. The staircases, catwalks and balconies are now aligned with the Z-level below, aswell as the new hull. I'll keep a backup on my local
